name: Automation Testing Parallel
on:
  push
    
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build Docker image
        run: |
          cd docker
          docker build -t angular_image .
          docker images
          
  runContainer:
    runs-on: ubuntu-latest
    needs: buildImage 
    services:
      my-container:
        image: angular_image:latest
        options: 
          --name angular_container
          -p 4200:4200 
    steps:
      - name: Step 1
        run: echo "This step runs on the job's primary container"
