name: Sharing image between two jobs
on:
   workflow_dispatch:
    
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build Docker image
        run: |
          cd docker
          docker build -t angular_image .
          docker images
          
  runContainer:
    runs-on: ubuntu-latest
    needs: buildImage 
    services:
      my-container:
        image: angular_image
        options: 
          --name angular_container
          -p 4200:4200 
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Step 1
        run: |
          docker ps -a
          echo "This step runs on the job's primary container"
