name: Automation Testing Parallel
on:
 push
    
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build and run Docker container
        run: |
          cd docker
          docker build -t angulerImage .
          ls
          
  runContainer:
    runs-on: ubuntu-latest
    needs: buildImage 
    services:
      my-container:
        image: angulerImage:latest
        options: 
          --name angulerContainer
          -p 4200:4200 
    steps:
      - name: Build and run Docker container
        run: |
            output="done"
            echo "::set-output name=output::$output"
      - name: Step 1
        run: echo "This step runs on the job's primary container"

      # - name: Step 2
      #   run: echo "This step runs on the same container as the first step"
      #   container: angulerContainer
