name: Build IAC

on:
 workflow_dispatch:
    inputs:
      Region:
        description: 'Enter the region'
        required: true
        default: 'us-west-2'
      cidr_block:
        description: "Enter Main-VPC cidr block"
        required: true
        default: '11.0.0.0/16'
    
 #push:
   # branches:
   #   - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
     TF_region: ${{github.event.inputs.Region}}
     TF_cidr_block: ${{github.event.inputs.cidr_block}}
     TF_access_key: ${{secrets.ACCESS_KEY}}
     TF_secret_key: ${{secrets.SECRET_KEY}}
    

    steps:
       
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: 0.15.4  

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ${{ github.event.inputs.region }}

    - name: Initialize Terraform
      run: |
        cd src
        terraform init 
        terraform validate

          
    - name: Apply Infrastructure
      run: |
          terraform plan -var="region=${TF_region}" -var="cidr_block=${TF_cidr_block}" -var="access_key=${TF_access_key}" -var="secret_key=${TF_secret_key}"
          terraform --auto-approve apply
         
        


      
