name: Build IAC

on:
 workflow_dispatch:
    inputs:
      Region:
        description: 'Enter the region'
        required: true
        default: 'us-west-2'
      cidr_block:
        description: "Enter Main-VPC cidr block"
        required: true
        default: '10.0.0.0/16'
    
 #push:
   # branches:
   #   - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
     TF_region: ${{  github.event.inputs.region}}
     TF_cidr_bloch: ${{  github.event.inputs.cidr_block}}
     TF_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
     TF_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    

    steps:
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: 0.15.4
    
    - name: Checkout code
      uses: actions/checkout@v2
          
    - name: deploy infrastructure
      run: |
          cd /src
          terraform init
          terraform plan
          terraform --auto-approve apply
          
        


      
