name: Build IAC

on:
 workflow_dispatch:
    inputs:
      Region:
        description: 'Enter the region'
        required: true
        default: 'us-west-2'
      cidr_block:
        description: "Enter Main-VPC cidr block"
        required: true
        default: '11.0.0.0/16'
      # name:
      #   description: "Enter backend name block"
      #   required: true
      #   default: 'keyname'
    
 #push:
   # branches:
   #   - main

jobs:

  state:
    name: "S3-State"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 0.15.4
      
      - name: Creating S3 
        run: |
          cd src/bootstrab
          terraform init
          terraform apply -auto-approve -var="region=${{github.event.inputs.Region}}"
 

  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    needs: state
    environment:
      name: Dev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 0.15.4


      - name: Terraform Init
        id: init
        run: |
          cd src
          terraform init
   #       -reconfigure -backend-config="bucket=terraform.tfstate-bucket" -backend-config="key=${{ github.event.inputs.name }}" -backend-config="region=${{ github.event.inputs.Region }}"
          

          
      # - name: Terraform Plan
      #   id: plan
      #   run: |
      #     cd src
      #     terraform plan -var="region=${{ github.event.inputs.Region }}" -var="cidr_block=${{ github.event.inputs.cidr_block }}"  


      # - name: Terraform Apply
      #   run: |
      #     cd primary_services_code
      #     terraform apply -auto-approve -var="region=${{ github.event.inputs.Region }}" -var="cidr_block=${{ github.event.inputs.cidr_block }}"  


        


      
