name: Build IAC

on:
 workflow_dispatch:
    inputs:
      Region:
        description: 'Enter the region'
        required: true
        default: 'us-west-2'
      cidr_block:
        description: "Enter Main-VPC cidr block"
        required: true
        default: '11.0.0.0/16'
    
 #push:
   # branches:
   #   - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment:
      name: Dev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.Region }}

      - name: Terraform Init
        id: init
        run: |
          cd src
          terraform init 
          
      - name: Terraform Plan
        id: plan
        run: |
          cd src
          terraform plan -var="region=${{ github.event.inputs.Region }}" -var="cidr_block=${{ github.event.inputs.cidr_block }}"  


      - name: Terraform Apply
        run: |
          cd primary_services_code
          terraform apply -auto-approve -var="region=${{ github.event.inputs.Region }}" -var="cidr_block=${{ github.event.inputs.cidr_block }}"  


        


      
