name: Test sending mails
on: 
  push:
    branches:
      - main
jobs:
  send_email:
    runs-on: ubuntu-latest
    steps: 
    - name: Create MongoDB container
      run: |
          echo "running mongodb container script..."
    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: mr3508570@gmail.com
        password: SafeSide@97166238
        # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        # comma-separated string, send email to
        to: mohamed.ramadan.bakry@vultara.com
        # from email name
        from: John Doe
