name: Cereate S3

on:
 workflow_dispatch:
  

    
jobs:
 
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment:
      name: Dev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 0.15.4


      - name: Terraform Init
        id: init
        run: |
          cd testDir
          terraform init 

          
      - name: Terraform Plan
        id: plan
        run: |
          cd testDir
          terraform plan


      - name: Terraform Apply
        run: |
          cd testDir
          terraform apply -auto-approve   

  
