name: Build IAC

on:
 workflow_dispatch:
    inputs:
      name:
        description: 'Enter Customer Name'
        default: 'ramadan'
        required: true
      Region:
        description: 'Enter the region'
        required: true
        default: 'us-west-2'
      cidr_block:
        description: "Enter Main-VPC cidr block"
        required: true
        default: '11.0.0.0/16'
      
      ami-type:
            description: 'Enter the AMI Type for EC2 Instance Scheduler'
            default: 'ami-008fe2fc65df48dac'
            required: true
      instance-type:
          description: 'Enter the Intance Type for EC2 Instance Scheduler'
          default: 't2.micro'
          required: true
      
    
jobs:

  state:
    name: "S3-State"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 0.15.4
      
      - name: Creating S3 
        run: |
          cd testDir
          terraform init
          terraform apply -auto-approve -var="region=${{github.event.inputs.Region}}"
 
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    needs: state
    environment:
      name: Dev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 0.15.4


      - name: Terraform Init
        id: init
        run: |
          cd testDir
          terraform init 

          
      - name: Terraform Plan
        id: plan
        run: |
          cd testDir
          terraform plan


      - name: Terraform Apply
        run: |
          cd testDir
          terraform apply -auto-approve   

  
